[CmdletBinding()]
param(
    [string]$Path = (Join-Path $PSScriptRoot "..\doc_classes\TdJson.xml"),
    [string]$GodotPath = (Join-Path $PSScriptRoot "..\gen\godot.exe"),
    [string]$ProjectPath = (Join-Path $PSScriptRoot "..\example")
)

function Get-PublicMethodNames([string]$XmlPath) {
    [xml]$xml = Get-Content -Raw $XmlPath
    return @(
        $xml.class.methods.method |
        Where-Object { $_.name -and $_.name -notlike "_*" } |
        ForEach-Object { [string]$_.name }
    )
}

$readyMethods = @(Get-PublicMethodNames $Path | Sort-Object -Unique)
$generatedDirectory = Join-Path ([System.IO.Path]::GetTempPath()) ("godot-tdlib-docs-" + [guid]::NewGuid())

try {
    New-Item -ItemType Directory -Path $generatedDirectory -Force | Out-Null
    $godotProcess = Start-Process `
        -FilePath (Resolve-Path $GodotPath) `
        -ArgumentList @(
            "--path", (Resolve-Path $ProjectPath),
            "--doctool", $generatedDirectory,
            "--gdextension-docs"
        ) `
        -Wait `
        -PassThru `
        -NoNewWindow
    if ($godotProcess.ExitCode -ne 0) {
        throw "Godot documentation generation failed with exit code $($godotProcess.ExitCode)"
    }
    $generatedPath = Get-ChildItem -Path $generatedDirectory -Filter "TdJson.xml" -File -Recurse |
        Select-Object -First 1 -ExpandProperty FullName
    if ([string]::IsNullOrWhiteSpace($generatedPath)) {
        $generatedFiles = @(Get-ChildItem -Path $generatedDirectory -File -Recurse |
            ForEach-Object { $_.FullName })
        throw "Godot did not generate TdJson.xml. Generated files: $($generatedFiles -join ', ')"
    }

    $generatedMethods = @(Get-PublicMethodNames $generatedPath | Sort-Object -Unique)
    $missing = @(Compare-Object -ReferenceObject $readyMethods -DifferenceObject $generatedMethods |
        Where-Object SideIndicator -eq '<=' |
        ForEach-Object InputObject)
    $extra = @(Compare-Object -ReferenceObject $readyMethods -DifferenceObject $generatedMethods |
        Where-Object SideIndicator -eq '=>' |
        ForEach-Object InputObject)

    if ($missing.Count -gt 0 -or $extra.Count -gt 0) {
        if ($missing.Count -gt 0) {
            Write-Error ("Methods present in ready documentation but missing from generated documentation: " + ($missing -join ", "))
        }
        if ($extra.Count -gt 0) {
            Write-Error ("Methods generated by Godot but missing from ready documentation: " + ($extra -join ", "))
        }
        exit 1
    }

    Write-Host ("Documentation methods match: {0} public methods." -f $readyMethods.Count)
}
finally {
    Remove-Item -Path $generatedDirectory -Recurse -Force -ErrorAction SilentlyContinue
}
