[CmdletBinding()]
param(
    [string]$Path = (Join-Path $PSScriptRoot "..\doc_classes\TdJson.xml"),
    [string]$SourcePath = (Join-Path $PSScriptRoot "..\src\tdjson.cpp"),
    [string]$GeneratedPath = ""
)

function Get-PublicMethodNames([string]$XmlPath) {
    [xml]$xml = Get-Content -Raw $XmlPath
    return @(
        $xml.class.methods.method |
        Where-Object { $_.name -and $_.name -notlike "_*" } |
        ForEach-Object { [string]$_.name }
    )
}

$readyMethods = @(Get-PublicMethodNames $Path | Sort-Object -Unique)
$registeredMethods = @(
    Select-String -Path $SourcePath -Pattern 'D_METHOD\(\s*"([^"]+)"' -AllMatches |
    ForEach-Object { $_.Matches } |
    ForEach-Object { $_.Groups[1].Value } |
    Where-Object { $_ -notlike "_*" } |
    Sort-Object -Unique
)

if ($registeredMethods.Count -eq 0) {
    throw "No registered TdJson methods found in $SourcePath"
}

$keepGeneratedDocs = -not [string]::IsNullOrWhiteSpace($GeneratedPath)

 $missing = @(Compare-Object -ReferenceObject $readyMethods -DifferenceObject $registeredMethods |
        Where-Object SideIndicator -eq '<=' |
        ForEach-Object InputObject)
    $extra = @(Compare-Object -ReferenceObject $readyMethods -DifferenceObject $registeredMethods |
        Where-Object SideIndicator -eq '=>' |
        ForEach-Object InputObject)

    if ($missing.Count -gt 0 -or $extra.Count -gt 0) {
        if ($missing.Count -gt 0) {
            Write-Error ("Methods present in ready documentation but missing from generated documentation: " + ($missing -join ", "))
        }
        if ($extra.Count -gt 0) {
            Write-Error ("Methods generated by Godot but missing from ready documentation: " + ($extra -join ", "))
        }
        exit 1
    }

    if ($keepGeneratedDocs) {
        $generatedDirectory = [System.IO.Path]::GetFullPath($GeneratedPath)
        New-Item -ItemType Directory -Path $generatedDirectory -Force | Out-Null
        @(
            "TdJson documentation check passed."
            "Public methods: $($readyMethods.Count)"
            "Source: $SourcePath"
        ) | Set-Content -Path (Join-Path $generatedDirectory "check.txt")
    }
Write-Host ("Documentation matches registered TdJson API: {0} public methods." -f $readyMethods.Count)
